name: Docker Build and Push

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ github.repository }}:${{ github.ref_name }}
            ${{ github.repository }}:latest
