on:
  workflow_dispatch:
    inputs:
      tag:
        description: Docker Tag
        required: true
  workflow_run:
    workflows:
      - docker-build-push
    types:
      - completed

jobs:
  deploy:
    name: Deploy to VKE

    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      namespace: discord

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.VKE_TESTNET_KUBECONFIG }}

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Configure K8s Cluster Access for VKE
        run: |
          echo $VKE_TESTNET_KUBECONFIG > ./kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
        env:
          VKE_TESTNET_KUBECONFIG: ${{ secrets.VKE_TESTNET_KUBECONFIG }}

      - name: Create K8s Secrets
        run: |
          echo "Updating Bitcoin Bot Secret"
          kubectl delete secret discord-bitcoin-bot-secrets --namespace=${{ env.namespace }}
          kubectl create secret generic discord-bitcoin-bot-secrets \
          --from-literal=BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
          --from-literal=PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
          --from-literal=CLIENT_ID=${{ secrets.CLIENT_ID }} \
          --from-literal=GUILD_ID=${{ secrets.GUILD_ID }} \
          --from-literal=LOG_CHANNEL_ID=${{ secrets.LOG_CHANNEL_ID }} \
          --from-literal=SATS_AMOUNT=${{ vars.SATS_AMOUNT }} \
          --from-literal=FAUCET_COOL_DOWN=${{ vars.FAUCET_COOL_DOWN }} \
          --namespace=${{ env.namespace }}

          echo "Restarting Bot"
          kubectl -n discord rollout restart deployment discord-bitcoin-testnet-bot-deployment

          echo "Bot Status"
          kubectl -n discord rollout status deployment/discord-bitcoin-testnet-bot-deployment

      - name: Dockerhub Secrets
        run: |
          if kubectl get secret dockerhub-secret --namespace=${{ env.namespace }}; then
            echo "Dockerhub Secret already exists"
          else
            echo "Creating Dockerhub Secret"
            kubectl create secret docker-registry dockerhub-secret \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKER_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_PASSWORD }} \
            --docker-email=${{ secrets.DOCKER_EMAIL }} \
            --namespace=${{ env.namespace }}
          fi

      - if: success()
        name: Update Image Tag in deployment
        run: |
          kustomize edit set image hemilabs/discord-bitcoin-testnet-bot:latest=hemilabs/discord-bitcoin-testnet-bot:${{ env.TAG }}
          kustomize edit set namespace ${{ env.namespace }}
        working-directory: ./kustomize
        env:
          TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.event.workflow_run.head_branch }}

      - name: Deploy to VKE
        run: kubectl apply -k ./kustomize
